### ISSUE TITLE
What are the director credentials?

### ISSUE THREAD

**Issue by akoranne** [concourse/concourse-bosh-deployment#10]
I am using on virtualbox. I had to shut the vm down and when I restarted it, concourse services did not start.

Is there a `director` vm that is spun up as part of this bosh deployment? And what are the credentials for me to login?

**Comment by cppforlife** [comment]
we havent had a chance to fix rebooting issue yet. vbox unfortunately does some weird things with disks and bosh agent isnt able to properly mount them. our recommended approach is to rerun command you ve initially used to strat the vm. if it says no chnages made , remove "manifest checksum" from the saved state file, and rerun.

**Comment by jtarchie** [comment]
To add on, the `bosh create-env` does not deploy a bosh director unless you use `bosh-deployment`. The `concourse-deployment` just deploys the concourse processes using runc containers.

**Comment by cxhercules** [comment]
@akoranne if you use the  [jumpbox](https://github.com/concourse/concourse-deployment/blob/master/jumpbox.yml) ops file in repo now you can use that to log in. You will find the credentials in vbox-creds.yml file.

**Comment by akoranne** [comment]
Thank you @cxhercules

**Comment by vito** [comment]
We now document this behavior in the new [`single-vm` README](https://github.com/concourse/concourse-deployment/blob/master/single-vm/README.md). See https://github.com/concourse/concourse-deployment/issues/15#issuecomment-346084230 for more background.
