### ISSUE TITLE
versions.yml references versions that don't yet exist

### ISSUE THREAD

**Issue by jpalermo** [concourse/concourse-bosh-deployment#123]
Currently versions.yml references concourse release version 4.2.2 but the master branch of concourse release is still 4.2.1 and 4.2.2 doesn't yet exist on bosh.io.

Can the process be changed such that there is a branch of concourse-bosh-deployment that is valid for deploying?

**Comment by taylorsilva** [comment]
Currently not an issue. There are also `release/x.x.x` branches that you can use.
