### ISSUE TITLE
No space left on the device

### ISSUE THREAD

**Issue by VicYP** [concourse/concourse-bosh-deployment#127]
Uploading ops manager and Pulling the image from pcfnorm.
I got no space left on device.
The situation is concouse worker device /dev/loop0 just have 8.2GB and file system
/var/vcap/data/Baggageclaim/volumes will be occupied fully. no more space for docker image.

**Comment by sapient007** [comment]
resize your worker should fix this

**Comment by vito** [comment]
yep. 8GB is not enough. you need more space.
