### ISSUE TITLE
GitLab Auth included in this BOSH release?

### ISSUE THREAD

**Issue by djvdorp** [concourse/concourse-bosh-deployment#128]
According to the Concourse.ci documentation page, GitLab Auth is a supported option for Configuring Auth Providers. Is this included in this particular BOSH release, I was unable to find this out easily?

I only saw these configs for Github here:
```
./cluster/operations/github-auth.yml
./cluster/operations/github-enterprise-auth.yml
```

See also:
https://concourse-ci.org/install.html#gitlab-auth-config
https://concourse-ci.org/authentication.html#gitlab-auth

**Comment by vito** [comment]
merged https://github.com/concourse/concourse-bosh-deployment/pull/161
