### ISSUE TITLE
concourse lite install error

### ISSUE THREAD

**Issue by betht1220** [concourse/concourse-bosh-deployment#130]

**Comment by betht1220** [comment]
Concourse lite install almost finished when it ran into the error with "merge". I've searched around, and it seems indication of error in the code. Any idea how to fix this? - Thanks

Deploying:
  Building state for instance 'concourse/0':
    Rendering job templates for instance 'concourse/0':
      Rendering templates for job 'baggageclaim/cf2757e36c267b4df3bc2cab3437cc6be632a070':
        Rendering template src: permit_device_control, dst: bin/permit_device_control:
          Rendering template src: /Users/dragon/.bosh/installations/eb4e3396-66fd-4434-7bbf-d267e160cf2f/tmp/bosh-release-job977808114/templates/permit_device_control, dst: /Users/dragon/.bosh/installations/eb4e3396-66fd-4434-7bbf-d267e160cf2f/tmp/rendered-jobs999986073/bin/permit_device_control:
            Running ruby to render templates:
              Running command: 'ruby /Users/dragon/.bosh/installations/eb4e3396-66fd-4434-7bbf-d267e160cf2f/tmp/erb-renderer141401636/erb-render.rb /Users/dragon/.bosh/installations/eb4e3396-66fd-4434-7bbf-d267e160cf2f/tmp/erb-renderer141401636/erb-context.json /Users/dragon/.bosh/installations/eb4e3396-66fd-4434-7bbf-d267e160cf2f/tmp/bosh-release-job977808114/templates/permit_device_control /Users/dragon/.bosh/installations/eb4e3396-66fd-4434-7bbf-d267e160cf2f/tmp/rendered-jobs999986073/bin/permit_device_control', stdout: '', stderr: '/Users/dragon/.bosh/installations/eb4e3396-66fd-4434-7bbf-d267e160cf2f/tmp/erb-renderer141401636/erb-render.rb:11:in `merge!': no implicit conversion of nil into Hash (TypeError)
	from /Users/dragon/.bosh/installations/eb4e3396-66fd-4434-7bbf-d267e160cf2f/tmp/erb-renderer141401636/erb-render.rb:11:in `recursive_merge!'
	from /Users/dragon/.bosh/installations/eb4e3396-66fd-4434-7bbf-d267e160cf2f/tmp/erb-renderer141401636/erb-render.rb:34:in `initialize'
	from /Users/dragon/.bosh/installations/eb4e3396-66fd-4434-7bbf-d267e160cf2f/tmp/erb-renderer141401636/erb-render.rb:197:in `new'
	from /Users/dragon/.bosh/installations/eb4e3396-66fd-4434-7bbf-d267e160cf2f/tmp/erb-renderer141401636/erb-render.rb:197:in `<main>'
':
                exit status 1

Exit code 1

**Comment by dohq** [comment]
sorry for my poor english.
Please add for ops-file `concourse-bosh-deployment/lite/operations/debug.yml`
I suceeded deploy concourse-lite.

thanks

**Comment by vito** [comment]
Sorry but we don't really support the lite deployment method to the extent that we can debug issues like this.

**Comment by a09-capf** [comment]
I face same error.
The cause of this issue looks like https://github.com/cloudfoundry/bosh-cli/issues/240 .
