### ISSUE TITLE
Post https://mbus:<redacted>@54.190.214.107:6868/agent: dial tcp 54.190.214.107:6868: i/o timeout

### ISSUE THREAD

**Issue by ghost** [concourse/concourse-bosh-deployment#136]
We have used this command to deploy concourse-lite 
 bosh2 create-env concourse.yml   -o ./infrastructures/aws.yml   -l ../versions.yml   --vars-store creds.yml   --state state.json   -v internal_cidr=10.x.x.x/24   -v internal_gw=10.x.x.x   -v internal_ip=10.x.x.x   -v public_ip=x.x.x.x

Facing the following error after running the above command:
Deploying:
  Creating instance 'concourse/0':
    Waiting until instance is ready:
      Post https://mbus:<redacted>@54.190.214.107:6868/agent: dial tcp 54.190.214.107:6868: i/o timeout
Any suggestions are welcomed.

**Comment by vito** [comment]
Sorry but this sounds more like a support request than a bug - check the [BOSH init](https://bosh.io/docs/init-aws/) docs? It sounds like your security groups need to be configured to allow your machine to reach the VM's agent.
