### ISSUE TITLE
v.5.0.0 has an incorrect url to bpm release. 

### ISSUE THREAD

**Issue by pydctw** [concourse/concourse-bosh-deployment#146]
Hi,
While upgrading our concourse to 5.0, we noticed that v.5.0.0 has a wrong url to bpm release. 

v5.0.0
url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=((bpm_version))

`master` branch has the correct url.
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=((bpm_version))

Here is the link to the file. 
https://github.com/concourse/concourse-bosh-deployment/blob/4d882bc1a789aaea9baee0a4ae4bb672bd49d706/cluster/concourse.yml#L12

Could you help fix this?

**Comment by vito** [comment]
I've re-pointed the tag at `master`.
