### ISSUE TITLE
Upgrade concourse cluster from v 4.2.1 to v 5.0.0

### ISSUE THREAD

**Issue by manaspatkar2121** [concourse/concourse-bosh-deployment#147]

**Comment by manaspatkar2121** [comment]
I have a cluster deployment of Concourse with 1 web node, 1 postgres node and 3 worker nodes. I use bosh to provision these virtual machines.

I upgraded Concourse cluster deployment from v 4.2.1 to v 5.0.0. The "concourse worker" vms are successfully updated, however they never get registered with the "web" node.  The workers enter into a "Landing" state after the upgrade. Can anyone please look into it ?

**Comment by manaspatkar2121** [comment]
Has anyone seen this issue ?

**Comment by dohq** [comment]
Try recreate wroker instances.
I it went well.

**Comment by vito** [comment]
Hi - we use issues for feature requests and bug reports, but this looks more like a support request/question - please consider using our [forums](https://discuss.concourse-ci.org) instead.
