### ISSUE TITLE
VirtualBox Instructions are Broken

### ISSUE THREAD

**Issue by dmcauslan** [concourse/concourse-bosh-deployment#15]
I'm running OSX 10.12.6.

Bosh CLI: 2.0.28
VirtualBox: 5.1.26

Ran: `bosh create-env concourse.yml -o ./infrastructures/virtualbox.yml --vars-store vbox-creds.yml --state vbox-state.json -v internal_cidr=192.168.50.0/24 -v internal_gw=192.168.50.1 -v internal_ip=192.168.50.4 -v public_ip=192.168.50.4`

Output:
```
Parsing release set manifest '/Users/xxx/vm-work/concourse-deployment/concourse.yml':
  Evaluating manifest:
    - Expected to find variables:
        - bosh_virtualbox_cpi_sha1
        - bosh_virtualbox_cpi_version
        - concourse_sha1
        - concourse_version
        - garden_runc_sha1
        - garden_runc_version
        - stemcell_sha1
        - stemcell_version

Exit code 1
```

**Comment by piersy** [comment]
In the meantime you can checkout 8cce524b7dbb8d5dfa6c8e974c8a2eb70221f7d5 the current instructions work for that commit.

I also modified the concourse.yml to use custom dns servers and have a more up to date version of concourse.
```
diff --git a/concourse.yml b/concourse.yml
index d5ad237..432499e 100644
--- a/concourse.yml
+++ b/concourse.yml
@@ -3,9 +3,9 @@ name: concourse-paper-plane
 
 releases:
   - name: concourse
-    version: 3.0.1
-    sha1: ade4f7b6a939d3a47590006410aa89f69b4dbd1f
-    url: https://bosh.io/d/github.com/concourse/concourse?v=3.0.1
+    version: 3.3.4
+    sha1: 17bdc7dbdc8d2b642f6796e1eb542fb9b2e962e2
+    url: https://bosh.io/d/github.com/concourse/concourse?v=3.3.4
   - name: garden-runc
     version: 1.6.0
     sha1: 58fbc64aff303e6d76899441241dd5dacef50cb7
@@ -29,7 +29,7 @@ networks:
   - range: ((internal_cidr))
     gateway: ((internal_gw))
     static_ips: ((internal_ip))
-    dns: [8.8.8.8]
+    dns: [10.34.104.10, 10.34.104.11, 10.222.101.3]
 
 instance_groups:
 - name: concourse

```

That got it working for me.

**Comment by cxhercules** [comment]
So it is strange that this project seems to have been made to help get a concourse up and running quickly, but seems like for benefit of building this project via pipelines, everyone else got the shaft. @vito @clarafu 

Change https://github.com/concourse/concourse-deployment/commit/4fdc949b2032396f128cfa15cf24fb7eab060ab5 helped someone but made it a slightly more difficult to get up and going quickly. Maybe a utility to gather latest values would have been helpful too. 

Anyhow this is how I solved it, and used latest code. 

```
bosh2 create-env concourse.yml   \
-o ./infrastructures/virtualbox.yml  --vars-store vbox-creds.yml   \
--state vbox-state.json   -v internal_cidr=192.168.50.0/24   \
-v internal_gw=192.168.50.1  -v internal_ip=192.168.50.4  -v public_ip=192.168.50.4 \
-v bosh_virtualbox_cpi_sha1="537c77b087eeda859b1eb89553efa6f808214d50" \
-v bosh_virtualbox_cpi_version="0.0.12" \
-v concourse_sha1=b74f09223ff75ac97bbb22d6cb4773c1a76e8aec \
-v concourse_version=3.4.1 \
-v garden_runc_sha1=a153fd2b9d85d01772e9c6907b8c9e5005059c9e \
-v garden_runc_version=1.9.3 \
-v stemcell_sha1=34b06740d6804a491316185973c4b77c86b45e5c \
-v stemcell_version="'3445.2'"
```

or create a file named vars.yml with these values:
```
bosh_virtualbox_cpi_sha1: 537c77b087eeda859b1eb89553efa6f808214d50
bosh_virtualbox_cpi_version: "0.0.12"
concourse_sha1: b74f09223ff75ac97bbb22d6cb4773c1a76e8aec
concourse_version: 3.4.1
garden_runc_sha1: a153fd2b9d85d01772e9c6907b8c9e5005059c9e
garden_runc_version: 1.9.3
stemcell_sha1: 34b06740d6804a491316185973c4b77c86b45e5c
stemcell_version: "3445.2"
```
Then you can use the command like this:
```
bosh2 create-env concourse.yml   \
-o ./infrastructures/virtualbox.yml  --vars-store vbox-creds.yml   \
--state vbox-state.json   -v internal_cidr=192.168.50.0/24   \
-v internal_gw=192.168.50.1  -v internal_ip=192.168.50.4  -v public_ip=192.168.50.4 \
-l vars.yml
```

**Comment by vito** [comment]
Sorry for the breakage, y'all. We've had a bit of an existential crisis with this repo, as when we initially published it we weren't anticipating that people would perceive it as a vector for contributing and discovering various ways to deploy Concourse with BOSH - it was initially just our toolchain for generating our single-VM VirtualBox image, for publishing on its own.

I've just finished tidying things up a bit and making the README more honest to what our new goals are. The new [`single-vm` README](https://github.com/concourse/concourse-deployment/blob/master/single-vm/README.md) should now work out of the box.

Thanks for your patience!
