### ISSUE TITLE
bionic stemcell

### ISSUE THREAD

**Issue by poblin-orange** [concourse/concourse-bosh-deployment#232]
Xenial stemcell are soon coming unsupported. Should provide bionic stemcell ops files ?

**Comment by benjaminguttmann-avtq** [comment]
At least a test with bionic stemcell worked perfectly fine for us so far.

**Comment by o-orand** [comment]
This ops file can be use to switch to bionic: https://github.com/concourse/concourse-bosh-deployment/blob/master/cluster/operations/update-stemcell.yml

**Comment by taylorsilva** [comment]
Bosh.io still has them labelled as beta; are they good to default to? https://bosh.io/stemcells/

**Comment by tcdowney** [comment]
According to [this cf-dev post](https://lists.cloudfoundry.org/g/cf-dev/message/9290) they'll be moved out of Beta to GA _soon_.

Apparently there was an issue with garden-runc (https://github.com/cloudfoundry/garden-runc-release/issues/169) and Diego cells that was holding it back, but that's being resolved. I'm not sure if that garden issue would impact Concourse or not -- mostly just concerned with the fact that the Xenial stemcells will no longer receive security patches after April.

**Comment by benjaminguttmann-avtq** [comment]
@taylorsilva  Maybe you check this one as well => https://lists.cloudfoundry.org/g/cf-bosh/message/2728

**Comment by taylorsilva** [comment]
Looks like we should be good to start testing and shipping with the bionic stemcell then. I'll drop this issue in our backlog for next week.

**Comment by taylorsilva** [comment]
Can't see that I added it from this issue but it is there! -> https://project.concourse-ci.org/ under the ToDo column right now.

**Comment by davewalter** [comment]
Looks like the [bionic stemcell](https://bosh.io/stemcells#ubuntu-bionic) is GA now.
