### ISSUE TITLE
Empty versions.yml for 7.9.0 concourse release

### ISSUE THREAD

**Issue by rahulkj** [concourse/concourse-bosh-deployment#245]
Looks like the bot deleted the versions.yml contents. Could you please fix this?

**Comment by rahulkj** [comment]
the contents have been enabled in the main branch, but can you please retag the versions.yml in the 7.9.0 release?

**Comment by Kump3r** [comment]
We are also blocked by this, is someone working on this?

**Comment by xtremerui** [comment]
Should be fixed in https://github.com/concourse/concourse-bosh-deployment/pull/249

**Comment by Kump3r** [comment]
It is fixed for the 7.9.x branch, but can someone also fix the tag for 7.9.0?

**Comment by Kump3r** [comment]
Fixed
