### ISSUE TITLE
better default auth

### ISSUE THREAD

**Issue by cppforlife** [concourse/concourse-bosh-deployment#3]
currently uses `no_really_i_dont_want_any_auth`

**Comment by seadowg** [comment]
@cppforlife I'm a big fan of this staying for the Virtual Box option. I understand it's maybe not great for deploying to GCP but it's definitely what I'm usually wanting if I'm deploying locally or on a private network.

**Comment by jtarchie** [comment]
@cppforlife: PR for ops file to support that?

**Comment by vito** [comment]
ops files are now present and the user must specify one of them:

- https://github.com/concourse/concourse-deployment/blob/master/cluster/operations/no-auth.yml
- https://github.com/concourse/concourse-deployment/blob/master/cluster/operations/basic-auth.yml
- https://github.com/concourse/concourse-deployment/blob/master/cluster/operations/github-auth.yml
