### ISSUE TITLE
Add github releases to help with consuming this repo

### ISSUE THREAD

**Issue by patrick-huber-pivotal** [concourse/concourse-bosh-deployment#51]
Please add releases with version tags like the [vault bosh release](https://github.com/cloudfoundry-community/vault-boshrelease/releases) and [cfcr deployment](https://github.com/cloudfoundry-incubator/kubo-deployment/releases) have releases defined.

This helps a consumer of this repo pin their dependencies to a commit that the author intends to be consumed publicly instead of an arbitrary commit.

**Comment by vito** [comment]
We'll be tagging and adopting a `develop`/`master` branching scheme. I'm not sure at this point if we'll be making proper GitHub releases though with notes and such - we already have `concourse/concourse` for that. We'll may use it as a mechanism for communicating breaking changes, though, if that comes up (i.e. ones that go beyond just generating the manifest again).

If the tagging is enough to satisfy this feel free to close as #39 was already closed to deliver that same thing. If you see a ton of value in having more than just that, I'm happy to leave this open to collect :+1:'s.

**Comment by patrick-huber-pivotal** [comment]
The tagging will work. I'll go ahead and close.
