### ISSUE TITLE
commit 13bd74ff19d1d5d0e28ed557c0663d3cf4eb3864

### ISSUE THREAD

**Issue by jmcdice** [concourse/concourse-bosh-deployment#53]
Hi,

Attempting to deploy this release from a BOSH director deployed via bbl results in this error:

Task 9 | 03:43:40 | Preparing deployment: Preparing deployment (00:00:00)
                   L Error: Job 'worker' not found in Template table
Task 9 | 03:43:40 | Error: Job 'worker' not found in Template table

Reversing this change:
```
-    name: groundcrew
+    name: worker
```
in the two places it exists in cluster/concourse.yml fixes the error and I can deploy this release successfully:

Task 10 Started  Thu Mar 22 03:45:22 UTC 2018
Task 10 Finished Thu Mar 22 03:56:42 UTC 2018
Task 10 Duration 00:11:20
Task 10 done

Succeeded

**Comment by shashwathi** [comment]
@jmcdice : 

We had to rename a job from `groundcrew` --> `worker`. Consider using `concourse-bosh-deployment` tagged version with `concourse` release version. Previously we did not tag the manifest along with release but we have started after this breaking change.

**Comment by jmcdice** [comment]
Seems like this change has been reverted because of this issue:

https://github.com/concourse/concourse-bosh-deployment/commit/13bd74ff19d1d5d0e28ed557c0663d3cf4eb3864

**Comment by vito** [comment]
Yep, we're going to start doing `develop`/`master` and having `master` always point to the latest tagged release. Sorry for the noise! Still figuring things out with this repo.

**Comment by bulanbiru** [comment]
We had a very similar problem.  Our release was not correctly uploaded to blobstore.  We removed the release ```bosh delete-release concourse/3.13.0``` and re-ran the deploy to resolve.
