### ISSUE TITLE
cluster-creds.yml

### ISSUE THREAD

**Issue by agregory999** [concourse/concourse-bosh-deployment#58]
Does the documentation provide samples of this? It doesn't appear obvious how to create it.

**Comment by zmb3** [comment]
`--vars-store` files are created automatically if they don't already exist.

If your bosh has a config server (ie credhub), you should omit the `--vars-store` flag.  In this case, any generated credentials will be written to the config server rather than dumped to a yml file.

**Comment by jama22** [comment]
Closing because I think @zmb3 was about to help you with your question. Please fee free to re-open @agregory999
