### ISSUE TITLE
Postgres-release v28 has a data loss bug

### ISSUE THREAD

**Issue by joshzarrabi** [concourse/concourse-bosh-deployment#66]
We deployed a concourse using `concourse-deployment` with `postgres-release` deployed for our database, as recommended in the default manifest. When upgrading the stemcell, and thus recreating the db vm, we lost our data. I filed an issue here: https://github.com/cloudfoundry/postgres-release/issues/42 but thought it might be good to mention it here as well.

**Comment by vito** [comment]
Not much we can do about this but thanks for the notice. We auto-bump to latest of postgres-release in our pipeline, so any fixes they make should automatically make it here when we ship.
