### ISSUE TITLE
add credhub/vault for secret storage?

### ISSUE THREAD

**Issue by cppforlife** [concourse/concourse-bosh-deployment#7]

**Comment by jtarchie** [comment]
@cppforlife, is there a reason you are creating these issues on concourse-deployment rather than concourse core? This doesn't seem to be a specific to concourse-deployment. And we have done [vault](http://concourse.ci/creds.html), almost.

**Comment by cppforlife** [comment]
im aware of vault support, and i think this repo should enable it out of the box. these are not feature requests to concourse but rather configuration options that should be applied.

**Comment by zmb3** [comment]
I created an [ops file](https://github.com/zmb3/concourse-vault-deployment/blob/master/add-vault.yml) to add Vault.

I'd submit a PR, but it seems like most of them are sitting idle.  Let me know if there's interest and I'd be happy to put one together.

**Comment by jama22** [comment]
@zmb3 team's been playing a bit of catch up with some of our PRs in the non-core repos. I'd really appreciate it if you could submit the PR and we'll look at it asap. 

For now, I'm going to go ahead and close the issue @cppforlife , since @zmb3 opsfile should be enough to get you going

**Comment by drnic** [comment]
why is this repo non-core? is there a "core" way to deploy a cluster of concourse with uaa/credhub built in?

**Comment by drnic** [comment]
There are blog posts on Pivotal's internal Wings deployment. Are they using this repo for base manifest + ops files or a different collection? Are they using credhub for their credentials manager?
