### ISSUE TITLE
Github Enterprise Auth requires ca_cert

### ISSUE THREAD

**Issue by aegershman** [concourse/concourse-bosh-deployment#73]
[In the github-enterprise operator](https://github.com/concourse/concourse-bosh-deployment/blob/master/cluster/operations/github-enterprise-auth.yml) there is a param opened for changing the host.

However [on the doc site it claims that a `ca-cert` is required](https://concourse-ci.org/install.html#auth-config)

```
If you're configuring GitHub Enterprise, you'll also need to set the following flags:

    --github-host=github.example.com

    --github-ca-cert=/tmp/some-cert

The GitHub Enterprise host should not contain a scheme, or a trailing slash.
```

I'm running into some issues when upgrading our Concourse to 4.0, and I'm thinking the `ca-cert` might have something to do with it. I can update this later when I get more details / if adding a `ca-cert` helps

**Comment by xyloman** [comment]
,I was working with @aegershman when we logged this issue it turns out to be related to https://github.com/concourse/concourse/issues/2425
