### ISSUE TITLE
Any way to set Web UI timeout from bosh deployed concourse?

### ISSUE THREAD

**Issue by bmhkb4** [concourse/concourse-bosh-deployment#88]
^^

**Comment by vito** [comment]
?

Please spend a bit more time submitting issues like this - what do you mean by "web UI timeout"?

Can you ask in Discord or on the forums instead? GitHub issues are better off for bugs/feature requests, they're not great for support. https://discuss.concourse-ci.org/

**Comment by bmhkb4** [comment]
It automatically logs you out in 24 hours.  Not sure what other details you need, but thanks for the worthless reply and immediate closure.
